chore: invite Billlynch
open-feature/community pull request #239
Opened 2023-08-15 13:09 UTC by toddbaert

Billlynch has been working on some related JS stuff, and helping with the client spec.

2023-08-15 14:01 UTC, beeme1mr approved these changes

2023-08-15 14:02 UTC, beeme1mr requested changes
Let's wait until Bill approves this PR before we merge it.

2023-08-15 15:50 UTC, kinyoklion approved these changes

2023-08-21 13:23 UTC, Billlynch approved these changes
Thank you! :)

2023-08-21 13:35 UTC, beeme1mr approved these changes

2023-08-21 13:35 UTC, merged