Create Candidates-2023
open-feature/community pull request #261
Opened 2023-10-04 13:00 UTC by DavidPHirsch

adding files and process for governance committee elections

2023-10-09 09:18 UTC, DavidPHirsch commented
@beeme1mr can you also share this in the GC slack channel?

2023-10-17 12:57 UTC, DavidPHirsch commented
@open-feature/governance-board

2023-10-22 04:27 UTC, moredip approved these changes

2023-10-23 17:45 UTC, beeme1mr approved these changes

2023-10-26 08:42 UTC, dabeeeenster approved these changes

2023-10-27 05:14 UTC, AlexsJones requested changes

2023-10-27 05:14 UTC, AlexsJones commented on Elections/2023/Candidates.md
> +- [Alex Jones](https://github.com/AlexsJones), Canonical
```suggestion
- [Alex Jones](https://github.com/AlexsJones), AWS
```
TY!

2023-10-27 10:45 UTC, AloisReitbauer commented
This is not the same model as for OpenTelemetry? Is it?

2023-11-06 17:30 UTC, merged